#!/usr/bin/env python3
"""Export item-memory tables for bare-metal ARM HDC bench (sw/arm_bench_data.h)."""

from __future__ import annotations

import argparse
from pathlib import Path


def read_hex_table(path: Path, rows: int, words: int) -> list[list[str]]:
    lines = []
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s and not s.startswith("//"):
            lines.append(s)
    need = rows * words
    if len(lines) < need:
        raise ValueError(f"{path}: need {need} hex lines, got {len(lines)}")
    out: list[list[str]] = []
    idx = 0
    for _ in range(rows):
        row = []
        for _ in range(words):
            row.append(f"0x{int(lines[idx], 16):016x}ULL")
            idx += 1
        out.append(row)
    return out


def fmt_table(name: str, table: list[list[str]]) -> str:
    rows = len(table)
    cols = len(table[0]) if table else 0
    body = ",\n    ".join("{ " + ", ".join(r) + " }" for r in table)
    return f"static const u64 {name}[{rows}][{cols}] = {{\n    {body}\n}};"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("mem_dir", type=Path, help="directory with item_mem_*.mem")
    p.add_argument("output", type=Path, help="output .h path")
    p.add_argument("--words", type=int, default=16)
    args = p.parse_args()

    mem_dir = args.mem_dir.resolve()
    ch = read_hex_table(mem_dir / "item_mem_channel.mem", 4, args.words)
    feat = read_hex_table(mem_dir / "item_mem_feature.mem", 5, args.words)
    val = read_hex_table(mem_dir / "item_mem_value.mem", 16, args.words)

    out = [
        "/* Auto-generated by python_ref/tools/export_arm_bench_data.py — do not edit. */",
        "#ifndef ARM_BENCH_DATA_H",
        "#define ARM_BENCH_DATA_H",
        "",
        '#include "xil_types.h"',
        "",
        fmt_table("arm_im_channel", ch),
        "",
        fmt_table("arm_im_feature", feat),
        "",
        fmt_table("arm_im_value", val),
        "",
        "#endif /* ARM_BENCH_DATA_H */",
        "",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
