#!/usr/bin/env python3
"""Export narrow-core co-sim hex to a bare-metal C header (K=128, no mask)."""

from __future__ import annotations

import argparse
from pathlib import Path

from export_golden_c import fmt_u64, parse_meta, read_hex_lines, u64_array


def main() -> None:
    p = argparse.ArgumentParser(description="Export narrow golden co-sim hex to C header")
    p.add_argument("vecdir", type=Path, help="directory with core_proto_narrow.hex")
    p.add_argument("output", type=Path, help="output .h path")
    args = p.parse_args()

    vecdir = args.vecdir.resolve()
    meta = parse_meta(vecdir / "meta.txt")

    proto_lines = read_hex_lines(vecdir / "core_proto_narrow.hex")
    lvl_lines = read_hex_lines(vecdir / "core_levels.hex")
    exp_lines = read_hex_lines(vecdir / "core_expect.hex")

    n_class = int(meta.get("n_class", "8"))
    words64 = int(meta.get("k_words", meta.get("words", "2")))
    n_cases = len(exp_lines)
    if meta.get("count"):
        n_cases = min(n_cases, int(meta["count"]))

    if len(proto_lines) != n_class * words64:
        raise ValueError(
            f"core_proto_narrow.hex: expected {n_class * words64} lines, got {len(proto_lines)}"
        )
    if len(lvl_lines) < n_cases:
        raise ValueError(f"core_levels.hex: need >= {n_cases} lines, got {len(lvl_lines)}")

    lvl0: list[str] = []
    lvl1: list[str] = []
    lvl2: list[str] = []
    for line in lvl_lines[:n_cases]:
        packed = int(line, 16)
        lvl0.append(f"0x{packed & 0xFFFFFFFF:08x}U")
        lvl1.append(f"0x{(packed >> 32) & 0xFFFFFFFF:08x}U")
        lvl2.append(f"0x{(packed >> 64) & 0xFFFF:04x}U")

    expect = [f"0x{int(line, 16):08x}U" for line in exp_lines[:n_cases]]

    out: list[str] = [
        "/* Auto-generated by python_ref/tools/export_golden_narrow_c.py — do not edit. */",
        "#ifndef GOLDEN_VECTORS_NARROW_H",
        "#define GOLDEN_VECTORS_NARROW_H",
        "",
        '#include "xil_types.h"',
        "",
        "#define GOLDEN_NARROW                     1U",
        f"#define GOLDEN_N_CLASS                    {n_class}U",
        f"#define GOLDEN_WORDS64                      {words64}U",
        f"#define GOLDEN_N_CASES                    {n_cases}U",
        "",
        u64_array("golden_proto64", proto_lines),
        "",
        f"static const u32 golden_levels0[GOLDEN_N_CASES] = {{\n    "
        + ",\n    ".join(lvl0)
        + "\n};",
        "",
        f"static const u32 golden_levels1[GOLDEN_N_CASES] = {{\n    "
        + ",\n    ".join(lvl1)
        + "\n};",
        "",
        f"static const u32 golden_levels2[GOLDEN_N_CASES] = {{\n    "
        + ",\n    ".join(lvl2)
        + "\n};",
        "",
        f"static const u32 golden_expect[GOLDEN_N_CASES] = {{\n    "
        + ",\n    ".join(expect)
        + "\n};",
        "",
        "#endif",
        "",
    ]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out), encoding="utf-8")
    k_bits = meta.get("k_bits", str(words64 * 64))
    print(
        f"Wrote {args.output}  ({n_cases} cases, K={k_bits}, "
        f"seed={meta.get('seed', '?')})"
    )


if __name__ == "__main__":
    main()
