#!/usr/bin/env python3
"""Generate rtl/hdc_sel_pkg.sv — the baked gather table for the H1 narrow AM (#28/#29).

Option E hardwires the Fisher-selected bit positions into the AM operand routing.
`SEL[]` must be a synthesis-time constant, and it must be *exactly* the mask the
Python golden model and the board `.mem` files use, or RTL and golden silently diverge.

So this script does **not** re-derive the mask from scores. It reads the frozen mask
artefact and emits it verbatim, recording a SHA-256 of the mask bits in both the
generated package and a manifest so CI can assert they still agree.

Why re-deriving would be wrong: `mask_from_scores` breaks score ties by ascending
index, and the Fisher scores have heavy ties (only 257 of 1024 positions have a
nonzero score). At keep=0.125 the rank-128 boundary is a 4-way tie, so re-deriving
picks a different 2 of those 4 than the stored artefact does — a silent 2-bit
divergence. See --check.

Usage:
  python3 scripts/gen_sel_table.py                       # keep=0.125 -> rtl/hdc_sel_pkg.sv
  python3 scripts/gen_sel_table.py --keep 0.5
  python3 scripts/gen_sel_table.py --identity            # K=D, SEL[i]=i (co-sim identity pass)
  python3 scripts/gen_sel_table.py --check               # verify existing package vs artefact
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "python_ref"))

DEFAULT_NPZ = REPO / "results" / "protocol_v2" / "fisher_pooled.npz"
DEFAULT_PKG = REPO / "rtl" / "hdc_sel_pkg.sv"
DEFAULT_MANIFEST = REPO / "results" / "narrow_rtl" / "sel_table_manifest.json"
BITS_PER_WORD = 64

KEEP_TO_KEY = {1.0: "mask_keep_1_0", 0.5: "mask_keep_0_5", 0.125: "mask_keep_0_125"}


def mask_sha(mask: np.ndarray) -> str:
    return hashlib.sha256(np.packbits(mask.astype(np.uint8)).tobytes()).hexdigest()


def repo_rel(path: Path) -> str:
    """Repo-relative POSIX path when possible, else the resolved absolute path."""
    resolved = path.resolve()
    try:
        return resolved.relative_to(REPO).as_posix()
    except ValueError:
        return resolved.as_posix()


def load_mask(npz: Path, keep: float) -> tuple[np.ndarray, str]:
    if keep not in KEEP_TO_KEY:
        raise SystemExit(
            f"keep={keep} not in frozen artefact; available: {sorted(KEEP_TO_KEY)}\n"
            "  Add it to scripts/export_fisher_pooled.py and regenerate, rather than\n"
            "  re-deriving here (tie-break divergence — see module docstring)."
        )
    key = KEEP_TO_KEY[keep]
    data = np.load(npz)
    if key not in data:
        raise SystemExit(f"{npz} has no '{key}' (keys: {list(data.keys())})")
    return np.asarray(data[key]).astype(np.uint8), key


def tie_report(npz: Path, mask: np.ndarray) -> dict:
    """Quantify how much of this mask is an arbitrary tie-break rather than informed."""
    data = np.load(npz)
    if "scores" not in data:
        return {}
    scores = np.asarray(data["scores"], dtype=np.float64)
    sel = np.flatnonzero(mask)
    n = int(sel.size)
    zero_scored = int((scores[sel] == 0.0).sum())
    boundary = float(np.sort(scores)[::-1][n - 1]) if n else 0.0
    tied_at_boundary = int((scores == boundary).sum())
    return {
        "n_selected": n,
        "n_nonzero_scored_overall": int((scores > 0).sum()),
        "n_selected_with_zero_score": zero_scored,
        "boundary_score": boundary,
        "n_tied_at_boundary": tied_at_boundary,
        "fully_informed": zero_scored == 0,
    }


def emit_package(sel: np.ndarray, D: int, sha: str, source: str, keep: float) -> str:
    k_bits = int(sel.size)
    k_words = (k_bits + BITS_PER_WORD - 1) // BITS_PER_WORD
    idx_w = max(1, int(np.ceil(np.log2(D))))

    # Packed SEL_FLAT rather than an unpacked int array: portable across the older
    # SV front-ends this repo already works around (see popcount_am.sv header).
    # Entry i occupies SEL_FLAT[i*IDX_W +: IDX_W]; with a genvar index that is an
    # elaboration-time constant, so it collapses to fixed routing.
    chunks = ["{:0{w}b}".format(int(p), w=idx_w) for p in sel]
    flat_bits = "".join(reversed(chunks))  # entry 0 in the LSBs

    lines = [
        "// hdc_sel_pkg.sv -- GENERATED by scripts/gen_sel_table.py. DO NOT EDIT.",
        "//",
        "// Baked gather table for the H1 narrow AM datapath (issue #28, Option E).",
        "// The AM is physically K_BITS wide and reads only the Fisher-selected bit",
        "// positions; the gather is a fixed wire permutation, so it costs 0 LUT:",
        "//",
        "//   narrow_query[i] = enc_query[SEL(i)]",
        "//",
        "// popcount is invariant to bit relabeling, so this is bit-exact to the",
        f"// baseline masked distance popcount((q ^ p) & mask).  See",
        "// docs/H1_narrow_datapath_design.md and",
        "// scripts/verify_narrow_gather_equivalence.py.",
        "//",
        f"// source:     {source}",
        f"// keep_ratio: {keep}",
        f"// mask_sha256:{sha}",
        "",
        "package hdc_sel_pkg;",
        "",
        f"    localparam int D       = {D};",
        f"    localparam int K_BITS  = {k_bits};",
        f"    localparam int K_WORDS = {k_words};",
        f"    localparam int IDX_W   = {idx_w};",
        "",
        "    // Selected bit positions, packed IDX_W bits per entry, entry 0 in the LSBs.",
        f"    localparam logic [K_BITS*IDX_W-1:0] SEL_FLAT = {k_bits * idx_w}'b{flat_bits};",
        "",
        "    // Elaboration-time accessor: constant when `i` is a genvar/localparam.",
        "    function automatic int SEL(input int i);",
        "        SEL = SEL_FLAT[i*IDX_W +: IDX_W];",
        "    endfunction",
        "",
        "endpackage",
        "",
    ]
    return "\n".join(lines)


def parse_pkg_sha(path: Path) -> str | None:
    if not path.is_file():
        return None
    m = re.search(r"mask_sha256:([0-9a-f]{64})", path.read_text(encoding="utf-8"))
    return m.group(1) if m else None


def decode_pkg_sel(path: Path) -> np.ndarray:
    """Decode SEL_FLAT exactly the way the RTL indexes it.

    The RTL does `SEL_FLAT[i*IDX_W +: IDX_W]`, i.e. entry i lives at bit offset
    i*IDX_W counting from the LSB. Re-deriving the positions from the emitted
    literal catches a bit-packing bug in this generator, which would otherwise
    produce silently wrong hardware.
    """
    text = path.read_text(encoding="utf-8")

    def localparam_int(name: str) -> int:
        m = re.search(rf"localparam\s+int\s+{name}\s*=\s*(\d+)\s*;", text)
        if not m:
            raise SystemExit(f"{path}: could not parse localparam int {name}")
        return int(m.group(1))

    k_bits = localparam_int("K_BITS")
    idx_w = localparam_int("IDX_W")

    m = re.search(r"SEL_FLAT\s*=\s*(\d+)'b([01_]+)\s*;", text)
    if not m:
        raise SystemExit(f"{path}: could not parse SEL_FLAT literal")
    width = int(m.group(1))
    bits = m.group(2).replace("_", "")
    if width != k_bits * idx_w:
        raise SystemExit(f"{path}: SEL_FLAT width {width} != K_BITS*IDX_W {k_bits * idx_w}")
    if len(bits) != width:
        raise SystemExit(f"{path}: SEL_FLAT has {len(bits)} digits, expected {width}")

    value = int(bits, 2)
    out = np.empty(k_bits, dtype=np.int64)
    for i in range(k_bits):
        out[i] = (value >> (i * idx_w)) & ((1 << idx_w) - 1)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the baked SEL table (#28 Option E)")
    ap.add_argument("--mask-npz", type=Path, default=DEFAULT_NPZ)
    ap.add_argument("--keep", type=float, default=0.125)
    ap.add_argument("--out", type=Path, default=DEFAULT_PKG)
    ap.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    ap.add_argument(
        "--identity",
        action="store_true",
        help="emit K_BITS=D, SEL[i]=i for the #30 identity pass (must be bit-identical to baseline)",
    )
    ap.add_argument("--check", action="store_true", help="verify existing package matches the artefact")
    args = ap.parse_args()

    if args.identity:
        data = np.load(args.mask_npz)
        D = int(data["D"]) if "D" in data else 1024
        mask = np.ones(D, dtype=np.uint8)
        key = "identity"
        keep = 1.0
    else:
        mask, key = load_mask(args.mask_npz, args.keep)
        D = int(mask.size)
        keep = args.keep

    sel = np.flatnonzero(mask).astype(np.int64)
    sha = mask_sha(mask)
    source = f"{repo_rel(args.mask_npz)}:{key}"

    if args.check:
        have = parse_pkg_sha(args.out)
        if have is None:
            print(f"CHECK FAIL: no mask_sha256 in {args.out}")
            return 1
        if have != sha:
            print(f"CHECK FAIL: {args.out} sha256 {have} != artefact {sha}")
            print("  regenerate with: python3 scripts/gen_sel_table.py --keep", keep)
            return 1
        decoded = decode_pkg_sel(args.out)
        if decoded.size != sel.size or not np.array_equal(decoded, sel):
            print(f"CHECK FAIL: SEL_FLAT in {args.out} does not decode to the artefact mask")
            if decoded.size != sel.size:
                print(f"  decoded {decoded.size} entries, artefact has {sel.size}")
            else:
                bad = np.flatnonzero(decoded != sel)
                print(f"  {bad.size} entries differ, first at i={bad[0]}: "
                      f"pkg={decoded[bad[0]]} artefact={sel[bad[0]]}")
            return 1
        print(f"CHECK OK: {args.out} matches {source}")
        print(f"  mask sha256   {sha}")
        print(f"  SEL_FLAT decodes to {decoded.size} positions, identical to artefact")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit_package(sel, D, sha, source, keep), encoding="utf-8")

    ties = tie_report(args.mask_npz, mask) if not args.identity else {}
    manifest = {
        "issue": 28,
        "option": "E — baked bit-permutation + narrow AM",
        "source": source,
        "keep_ratio": keep,
        "D": D,
        "k_bits": int(sel.size),
        "k_words": (int(sel.size) + BITS_PER_WORD - 1) // BITS_PER_WORD,
        "mask_sha256": sha,
        "generated_package": repo_rel(args.out),
        "sel": sel.tolist(),
        "tie_analysis": ties,
    }
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote {args.out}")
    print(f"  source     {source}")
    print(f"  K_BITS     {sel.size}  ({manifest['k_words']} words of {BITS_PER_WORD})")
    print(f"  mask sha256 {sha}")
    if ties:
        print(
            f"  informed:  {ties['n_selected'] - ties['n_selected_with_zero_score']}"
            f"/{ties['n_selected']} selected bits have nonzero Fisher score"
        )
        if not ties["fully_informed"]:
            print(
                f"  WARNING: {ties['n_selected_with_zero_score']} selected bits are "
                f"zero-scored ties -- this mask is only partly informed"
            )
        if ties["n_tied_at_boundary"] > 1:
            print(
                f"  note: {ties['n_tied_at_boundary']} bits tie at the rank-{ties['n_selected']} "
                f"boundary score {ties['boundary_score']:.6f}; frozen artefact pins the choice"
            )
    print(f"Wrote {args.manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
