#!/usr/bin/env python3
"""
Convert core co-sim hex files to a bare-metal C header for ZedBoard golden test.

Usage:
    python export_golden_c.py <vecdir> <output.h>

Example:
    python export_golden_c.py ../vectors/cosim_core ../../sw/golden_vectors.h

Matches tb/tb_core_axi_cosim.sv $readmemh layout and proto32/mask32 packing.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def parse_meta(meta_path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not meta_path.exists():
        return out
    for line in meta_path.read_text(encoding="utf-8").splitlines():
        if "=" in line:
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def read_hex_lines(path: Path) -> list[str]:
    lines = []
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s and not s.startswith("//"):
            lines.append(s)
    return lines


def fmt_u64(hex_str: str) -> str:
    return f"0x{int(hex_str, 16):016x}ULL"


def u64_array(name: str, hex_lines: list[str]) -> str:
    vals = [fmt_u64(s) for s in hex_lines]
    body = ",\n    ".join(vals)
    return f"static const u64 {name}[{len(vals)}] = {{\n    {body}\n}};"


def main() -> None:
    p = argparse.ArgumentParser(description="Export golden co-sim hex to C header")
    p.add_argument("vecdir", type=Path, help="directory with core_*.hex")
    p.add_argument("output", type=Path, help="output .h path")
    args = p.parse_args()

    vecdir = args.vecdir.resolve()
    meta = parse_meta(vecdir / "meta.txt")

    proto_lines = read_hex_lines(vecdir / "core_proto.hex")
    mask_lines = read_hex_lines(vecdir / "core_mask.hex")
    lvl_lines = read_hex_lines(vecdir / "core_levels.hex")
    exp_lines = read_hex_lines(vecdir / "core_expect.hex")

    n_class = int(meta.get("n_class", "8"))
    words64 = int(meta.get("words", "16"))
    n_cases = len(exp_lines)
    if meta.get("count"):
        n_cases = min(n_cases, int(meta["count"]))

    if len(proto_lines) != n_class * words64:
        raise ValueError(
            f"core_proto.hex: expected {n_class * words64} lines, got {len(proto_lines)}"
        )
    if len(mask_lines) != words64:
        raise ValueError(f"core_mask.hex: expected {words64} lines, got {len(mask_lines)}")
    if len(lvl_lines) < n_cases:
        raise ValueError(f"core_levels.hex: need >= {n_cases} lines, got {len(lvl_lines)}")

    lvl0: list[str] = []
    lvl1: list[str] = []
    lvl2: list[str] = []
    for line in lvl_lines[:n_cases]:
        packed = int(line, 16)
        lvl0.append(f"0x{packed & 0xFFFFFFFF:08x}U")
        lvl1.append(f"0x{(packed >> 32) & 0xFFFFFFFF:08x}U")
        lvl2.append(f"0x{(packed >> 64) & 0xFFFF:04x}U")

    expect = [f"0x{int(line, 16):08x}U" for line in exp_lines[:n_cases]]

    out: list[str] = [
        "/* Auto-generated by python_ref/tools/export_golden_c.py — do not edit. */",
        "#ifndef GOLDEN_VECTORS_H",
        "#define GOLDEN_VECTORS_H",
        "",
        '#include "xil_types.h"',
        "",
        f"#define GOLDEN_N_CLASS   {n_class}U",
        f"#define GOLDEN_WORDS64     {words64}U",
        f"#define GOLDEN_N_CASES   {n_cases}U",
        "",
        u64_array("golden_proto64", proto_lines),
        "",
        u64_array("golden_mask64", mask_lines),
        "",
        f"static const u32 golden_levels0[GOLDEN_N_CASES] = {{\n    "
        + ",\n    ".join(lvl0)
        + "\n};",
        "",
        f"static const u32 golden_levels1[GOLDEN_N_CASES] = {{\n    "
        + ",\n    ".join(lvl1)
        + "\n};",
        "",
        f"static const u32 golden_levels2[GOLDEN_N_CASES] = {{\n    "
        + ",\n    ".join(lvl2)
        + "\n};",
        "",
        f"static const u32 golden_expect[GOLDEN_N_CASES] = {{\n    "
        + ",\n    ".join(expect)
        + "\n};",
        "",
        "#endif",
        "",
    ]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {args.output}  ({n_cases} cases, {n_class} classes, seed={meta.get('seed', '?')})")


if __name__ == "__main__":
    main()
